<?php 
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */

function maximus_preprocess_page(&$variables, $hook) 
{
  $variables['site_name'] = \Drupal::config('system.site')->get('name');
}

function maximus_theme_suggestions_page_alter(array &$suggestions, array $variables) 
{ 
  if ($node = \Drupal::routeMatch()->getParameter('node')) 
  {
    $suggestions[] = 'page__node__' . $node->getType();
  }
}

